# pyproject.toml für KEI-Agent Python SDK
# Moderne Python Package-Konfiguration nach PEP 518/621

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kei-agent-sdk"
version = "0.1.0"
description = "Enterprise-Grade Python SDK for KEI Agent Framework with Multi-Protocol Support and Comprehensive Documentation"
readme = "README.md"
license = {text = "MIT"}
authors = [
    {name = "KEI-Agent-Framework Team", email = "dev@kei-agent-framework.com"},
    {name = "Oliver Scharkowski", email = "o.scharkowski@oscharko.de"}
]
maintainers = [
    {name = "Oliver Scharkowski", email = "o.scharkowski@oscharko.de"}
]
keywords = [
    "ai", "agent", "multi-agent", "framework", "rpc", "stream", "bus", "mcp",
    "enterprise", "async", "distributed", "tracing", "monitoring", "resilience"
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Science/Research",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Topic :: System :: Distributed Computing",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Framework :: AsyncIO",
    "Typing :: Typed"
]
requires-python = ">=3.8"
dependencies = [
    # HTTP und WebSocket Clients
    "aiohttp>=3.8.0,<4.0.0",
    "httpx>=0.24.0,<1.0.0",
    "websockets>=11.0.0,<12.0.0",
    
    # Async und Utilities
    "pydantic>=2.0.0,<3.0.0",
    "typing-extensions>=4.0.0",
    
    # Tracing und Monitoring
    "opentelemetry-api>=1.20.0,<2.0.0",
    "opentelemetry-sdk>=1.20.0,<2.0.0",
    "opentelemetry-exporter-jaeger>=1.20.0,<2.0.0",
    "opentelemetry-exporter-zipkin-json>=1.20.0,<2.0.0",
    "opentelemetry-propagator-b3>=1.20.0,<2.0.0",
    
    # Retry und Circuit Breaker
    "tenacity>=8.2.0,<10.0.0",
    
    # Serialization
    "msgpack>=1.0.0,<2.0.0",
    
    # Utilities
    "packaging>=21.0",
    "python-dateutil>=2.8.0",

    # Enterprise Features
    "psutil>=5.9.0,<6.0.0",  # System monitoring
    "structlog>=23.1.0,<24.0.0",  # Structured logging
]

[project.optional-dependencies]
security = [
    "authlib>=1.2.0,<2.0.0",
    "cryptography>=41.0.0,<42.0.0",
    "pyopenssl>=23.0.0,<24.0.0"
]
dev = [
    "pytest>=7.4.0,<8.0.0",
    "pytest-asyncio>=0.21.0,<1.0.0",
    "pytest-cov>=4.1.0,<5.0.0",
    "pytest-mock>=3.11.0,<4.0.0",
    "pytest-benchmark>=4.0.0,<5.0.0",
    "ruff>=0.1.0,<1.0.0",  # Modern linter/formatter
    "mypy>=1.5.0,<2.0.0",
    "bandit>=1.7.0,<2.0.0",  # Security linting
    "pre-commit>=3.4.0,<4.0.0",
    "twine>=4.0.0,<5.0.0",  # Package publishing
    "build>=0.10.0,<1.0.0"  # Package building
]
docs = [
    "mkdocs>=1.5.0,<2.0.0",
    "mkdocs-material>=9.4.0,<10.0.0",
    "mkdocs-autorefs>=0.5.0,<1.0.0",
    "mkdocstrings[python]>=0.23.0,<1.0.0",
    "mkdocs-mermaid2-plugin>=1.1.0,<2.0.0",
    "mkdocs-git-revision-date-localized-plugin>=1.2.0,<2.0.0",
    "mkdocs-minify-plugin>=0.7.0,<1.0.0",
    "mkdocs-redirects>=1.2.0,<2.0.0"
]
all = [
    "kei-agent-sdk[security,dev,docs]"
]

[project.scripts]
kei-agent = "kei_agent.cli:main"

[project.urls]
Homepage = "https://docs.kei-agent-framework.com"
Documentation = "https://docs.kei-agent-framework.com"
Repository = "https://github.com/oscharko/kei-agent-python-sdk"
"Bug Tracker" = "https://github.com/oscharko/kei-agent-python-sdk/issues"
Changelog = "https://github.com/oscharko/kei-agent-python-sdk/blob/main/CHANGELOG.md"

# Tool-Konfigurationen

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["kei_agent*"]
exclude = ["tests*", "examples*"]

[tool.setuptools.package-data]
kei_agent = ["py.typed", "*.pyi"]

# Black Code Formatter
[tool.black]
line-length = 100
target-version = ['py38', 'py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
extend-exclude = '''
/(
  # directories
  \.eggs
  | \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
)/
'''

# isort Import Sorter
[tool.isort]
profile = "black"
line_length = 100
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true

# MyPy Type Checker
[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_no_return = true
warn_unreachable = true
strict_equality = true

[[tool.mypy.overrides]]
module = [
    "aiohttp.*",
    "websockets.*",
    "opentelemetry.*",
    "tenacity.*",
    "msgpack.*"
]
ignore_missing_imports = true

# Pytest Test Runner
[tool.pytest.ini_options]
minversion = "7.0"
addopts = "-ra -q --strict-markers --strict-config"
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "unit: marks tests as unit tests"
]

# Coverage.py
[tool.coverage.run]
source = ["kei_agent"]
omit = [
    "*/tests/*",
    "*/examples/*",
    "setup.py"
]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "def __repr__",
    "if self.debug:",
    "if settings.DEBUG",
    "raise AssertionError",
    "raise NotImplementedError",
    "if 0:",
    "if __name__ == .__main__.:"
]

[tool.coverage.html]
directory = "htmlcov"
